export { default as FacebookIcon } from "./facebook-icon.svg"
export { default as InstagramIcon } from "./instagram-icon.svg"
export { default as TikTokIcon } from "./tiktok-icon.svg"
export { default as YouTubeIcon } from "./youtube-icon.svg"
export { default as ArrowRightIcon } from "./arrow-right-circle-icon.svg"
export { default as ArrowLeftIcon } from "./arrow-left-circle-icon.svg"
