import { RecipeDetail } from "@interfaces/interfaces";

export const recipesDetails: Record<string, RecipeDetail> = {
  '1': {
    id: '1',
    title: 'Rollitos de pechuga de pavo rellenos de hummus',
    description: "Disfruta de unos deliciosos rollitos de pechuga de pavo rellenos de hummus, perfectos para un almuerzo saludable y rápido.",    image: 'https://www.vidaenbalance.com/wp-content/uploads/2023/05/Rollitos-de-pechuga-de-pavo-rellenos-de-hummus-sobre-ensalada-de-farro-1.jpg',
    ingredients: [
      '1 taza de farro',
      '3 tazas de agua',
      '1 cucharadita de caldo de verdura en polvo',
      '4 cucharadas de aceite de oliva',
      '¼ de cebolla morada picada',
      '3 cucharadas de perejil picado',
      '2 jitomates picados',
      '½ chile serrano picado',
      '2 limones',
      '1 taza de hummus',
      '1 paquete de Pechuga de Pavo San Rafael® Balance®',
      '½ taza de hojas pequeñas de albahaca',
      'Sal y pimienta al gusto'
    ],
    preparation: [
      'Coloca el farro en una olla mediana con el agua. Deja remojar durante 20 minutos. Agrega el caldo de verdura, tapa y cuece a fuego alto hasta que comience a hervir. Baja el fuego al mínimo y cuece durante 20 minutos. Agrega el aceite de oliva y deja enfriar.',
      'Integra la cebolla morada, perejil, jitomate, chile serrano y jugo de limón, salpimienta.',
      'Rellena las rebanadas de Pechuga de Pavo San Rafael® Balance® con el hummus y enrolla. Sirve sobre una base de la mezcla anterior y termina con las hojas de albahaca.'
    ],
    timePrep: '25 minutos',
    portions: '5 porciones',
    difficulty: 'Fácil',
    datePublished: '2025-01-01'
  },
  '2': {
    id: '2',
    title: 'Sándwich abierto de pechuga de pavo con ensalada de col y pera',
    description: 'Delicioso sándwich abierto con pechuga de pavo, ensalada de col y pera, perfecto para una comida ligera y saludable.',
    image: 'https://www.vidaenbalance.com/wp-content/uploads/2023/05/Sandwich-abierto-de-pechuga-de-pavo-con-ensalada-de-col-y-pera-1.jpg',
    ingredients: [
      '8 rebanadas de pan Ezequiel',
      '4 cucharadas de cacahuates tostados',
      '½ taza de col morada fileteada',
      '½ taza de col blanca fileteada',
      '½ zanahoria en tiras delgadas',
      '2 coles de Bruselas picadas',
      '3 cucharadas de aceite de oliva',
      '1 limón',
      '1 pera verde',
      '1 paquete de Pechuga de Pavo San Rafael® Balance® Rebanadas Delgadas',
      '4 chiles chipotle adobados molidos',
      'Sal y pimienta al gusto',
    ],
    preparation: [
      'Tuesta el pan en una plancha a fuego medio.',
      'Mezcla los cacahuates con la col morada, col blanca, zanahoria, coles de Bruselas, aceite de oliva y jugo de limón, salpimienta.',
      'Rebana la pera en láminas delgadas',
      'Coloca un par de cucharadas de ensalada sobre las rebanadas de pan, después algunas láminas de pera y termina con 2 rebanadas de Pechuga de Pavo San Rafael® Balance®.',
      'Acompaña con el chipotle y sirve.',
    ],
    timePrep: '20 minutos',
    portions: '4 porciones',
    difficulty: 'Fácil',
    datePublished: '2025-01-01'
  },
  '3': {
    id: '3',
    title: 'Mitades de pan pita rellenas con pechuga de pavo, arúgula y salsa tzatziki',
    description: 'Disfruta de un platillo delicioso y saludable con estas mitades de pan pita rellenas de pechuga de pavo, arúgula y salsa tzatziki.',
    image: 'https://www.vidaenbalance.com/wp-content/uploads/2023/06/Mitades-de-pan-pita-rellenas-con-pechuga-de-pavo-arugula-y-salsa-tzatziki.webp',
    ingredients: [
      '1 taza de jocoque',
      '3 cucharadas de hierbabuena picada',
      '2 pepinillos frescos',
      '1 limón',
      '1 paquete de Pechuga de Pavo San Rafael® Balance®',
      '4 piezas de pan árabe',
      '1 taza de arúgula',
      'Sal y pimienta al gusto',
    ],
    preparation: [
      'Para la salsa tzatziki, ralla el pepinillo, agrega un poco de sal y deja reposar unos minutos. Exprime con ayuda de un trapo limpio y mezcla con el jocoque, hierbabuena y jugo de limón, salpimienta.',
      'Tuesta el pan ligeramente y corta a la mitad, rellena con algunas rebanadas de Pechuga de Pavo San Rafael® Balance® y arúgula.',
      'Acompaña con el tzatziki.',
    ],
    timePrep: '15 minutos',
    portions: '4 porciones',
    difficulty: 'Fácil',
    datePublished: '2025-01-01'
  },
  '4': {
    id: '4',
    title: 'Calabacitas rellenas de Pechuga de pavo San Rafael Balance® y piña',
    description: 'Disfruta de una comida ligera y deliciosa con estas calabacitas rellenas de Pechuga de pavo San Rafael Balance® y piña.',
    image: 'https://www.vidaenbalance.com/wp-content/uploads/2024/03/673x890-Calabacitas.jpg',
    ingredients: [
      '4 Calabacitas redondas',
      '1 Pechuga de pavo San Rafael Balance®',
      '2 rebanadas de piña',
      'Sal al gusto',
      'Pizca de azúcar',
    ],
    preparation: [
      'Cortamos la parte del tallo de las calabacitas y las incorporamos en agua caliente con una pizca de sal y una pizca de azúcar. Dejamos cocer durante 5 minutos; debemos girar las calabacitas para que su cocción sea completa. No sobre cocer para que no se hagan blanditas.',
      'Picamos la Pechuga de pavo San Rafael Balance® y las rebanadas de piña las picamos en pequeños cuadritos, integramos una pizca de sal y mezclamos. Sacamos las calabacitas del agua y le quitamos el relleno con una cuchara, sin dejar las paredes muy delgadas.',
      'Rellenamos las calabacitas con la mezcla de Pechuga de pavo San Rafael Balance® y piña y listo ¡Disfruta de este delicioso platillo!',
    ],
    timePrep: '20 minutos',
    portions: '4 porciones',
    difficulty: 'Media',
    datePublished: '2025-01-01'
  },
  '5': {
    id: '5',
    title: 'Molletes de camote y calabaza',
    description: 'Disfruta de la combinación perfecta de sabores con estos molletes de camote y calabaza.',
    image: 'https://www.vidaenbalance.com/wp-content/uploads/2024/06/MOLLETES-DE-CAMOTE-Y-CALABAZA-873x890-1.jpg',
    ingredients: [
      '1 camote',
      '1 calabaza',
      'Pechuga de Pavo rebanadas redondas San Rafael Balance®',
      '1 jitomate',
      '1 cebolla',
      '3 chiles toreados',
      '2 limones',
      '1 taza de frijoles refritos bayos',
    ],
    preparation: [
      'Coloca el camote y la calabaza en un sartén',
      'Una vez que estén cocidos por la parte de abajo, voltéalos y úntales los frijoles. Puedes agregar una pizca de sal a tu gusto.',
      'Una vez que estén asados por la parte de abajo, retíralos del sartén y ponles 3 rebanadas de pechuga de pavo rebanadas redondas San Rafael Balance®.',
      'Ponlos en un recipiente, añade uno o dos limones al gusto y comienza a mezclarlos.',
      'Agrega sal y pimienta al pico de gallo. Ahora sí, ¡Disfrútalo!',
    ],
    timePrep: '25-30 minutos',
    portions: '4 porciones',
    difficulty: 'Media',
    datePublished: '2025-01-01'
  },
  '6': {
    id: '6',
    title: 'Rollitos Thai',
    description: 'Disfruta de un aperitivo ligero y delicioso con estos rollitos Thai.',
    image: 'https://www.vidaenbalance.com/wp-content/uploads/2024/06/ROLLITOS-THAI-673x890-1.jpg',
    ingredients: [
      'Pechuga de pavo rebanadas redondas San Rafael Balance®',
      '1 Lechuga',
      '2 Zanahorias',
      '2 Pepinos',
      '2 Jícamas',
      'Dip de tu preferencia',
    ],
    preparation: [
      'Lava y desinfecta todas las verduras.',
      'Una vez que las verduras estén limpias, córtalas en tiras.',
      'Toma una rebanada de pechuga de pavo San Rafael Balance® rebanadas redondas y coloca las verduras sobre ella.',
      'Haz un rollito con los ingredientes.',
      'Acompaña con tu dip favorito.',
    ],
    timePrep: '15-20 minutos',
    portions: '4 porciones',
    difficulty: 'Fácil',
    datePublished: '2025-01-01'  },
  '7': {
    id: '7',
    title: 'Cocktail de Mango',
    description: 'Disfruta de un delicioso cóctel de mango, perfecto para acompañar tus reuniones.',
    image: 'https://www.vidaenbalance.com/wp-content/uploads/2024/06/COCKTAIL-CON-MANGO-673x890-1.jpg',
    ingredients: [
      '2 Mangos',
      '3 Chiles serranos',
      'Salchicha de pechuga de pavo San Rafael Balance®',
      'Pimienta',
      'Perejil',
      '1 Caja de tostadas saladas',
    ],
    preparation: [
      'Corta finamente las salchichas, el mango y los chiles serranos.',
      'Agrega sal y pimienta.',
      'Mezcla todos los ingredientes',
      'Coloca tus tostadas saladas en un plato.',
      'Una vez que tengas lista tu mezcla del cóctel, sírvela en tus tostadas.',
    ],
    timePrep: '15-20 minutos',
    portions: '4 porciones',
    difficulty: 'Fácil',
    datePublished: '2025-01-01'
  },
  '8': {
    id: '8',
    title: 'Aguacate relleno de arroz integral y salchicha de pavo',
    description: 'Disfruta de un aperitivo delicioso y saludable con este aguacate relleno de arroz integral y salchicha de pavo.',
    image: 'https://www.vidaenbalance.com/wp-content/uploads/2023/08/Aguacate-relleno-de-arroz-integral-y-salchicha-de-pavo.webp',
    ingredients: [
      '2 aguacates',
      '1 taza de arroz integral con cebada perla',
      '3 cucharadas de aceite de oliva',
      '4 cucharadas de cebolla picada',
      '1 rama de perejil',
      '½ cucharadita de comino',
      '2 ½ tazas de agua',
      '4 salchichas de Pavo San Rafael® Balance® en rodajas',
      '1 chile serrano rebanado',
      '2 jitomates picados',
      '1 taza de tomates cherry',
      '3 cucharadas de miel',
      '2 cucharadas de vinagre de manzana',
      'Sal y pimienta al gusto',
    ],
    preparation: [
      'Sofríe el arroz, cebolla, salchichas y comino en una olla mediana con el aceite de oliva, cuando comiencen a dorar agrega el agua y perejil, tapa y cuece a fuego medio durante 20 minutos. Deja enfriar por completo e integra el jitomate picado y chile serrano',
      'Mientras tanto, pela los aguacates y parte a la mitad. Mezcla la miel con vinagre de manzana y agrega un poco de sal y pimienta.',
      'Rellena las mitades de aguacate con la mezcla anterior, acompaña con los cherries y aderezo.',
    ],
    timePrep: '35-40 minutos',
    portions: '4 porciones',
    difficulty: 'Media',
    datePublished: '2025-01-01'
  },
  '9': {
    id: '9',
    title: 'Yakimeshi de Quinoa con Salchichas de Pavo San Rafael Balance®',
    description: 'Disfruta de un Yakimeshi saludable y lleno de sabor con esta receta de quinoa con salchichas de pavo San Rafael Balance®.',
    image: 'https://www.vidaenbalance.com/wp-content/uploads/2023/06/Yakimeshi-Recetas-673-890.jpg',
    ingredients: [
      '1 taza de quinoa cocida',
      '1 paquete de salchichas de pavo San Rafael Balance®',
      '1/2 cebolla',
      '2 dientes de ajo',
      '1 zanahoria pequeña',
      '1 trozo de apio con algunas hojas',
      '1 tallo de cebollín',
      '1 ají dulce o picante según tu gusto',
      '1 calabacín pequeño',
      'Sal',
      'Pimienta',
    ],
    preparation: [
      'Calienta un sartén profundo o una olla y saltea en aceite de oliva todos los vegetales que vayas a usar comenzando por la cebolla, el ajo y la zanahoria. Reserva el cebollín y unas hojas de apio para más adelante.',
      'Agrega la salchicha de pavo San Rafael Balance® picada en rodajas y deja que se cocine un par de minutos junto a los vegetales.',
      'Agrega sal, pimienta y si está muy seco, un poquito de agua (menos de ¼ de taza). Prueba el guiso y revisa que esté bien de sal y pimienta.',
      'Deja cocinar por 2 minutos. Incorpora la quinoa previamente cocida. Mezcla todo bien, agrega el cebollín y las hojas de apio, ambos picados bien pequeñito.',
      'Retira del fuego, sirve y disfruta este delicioso Yakimeshi de Quinoa con Salchichas de Pavo San Rafael Balance®',
    ],
    timePrep: '25-30 minutos',
    portions: '4 porciones',
    difficulty: 'Media',
    datePublished: '2025-01-01'
  },
  '10': {
    id: '10',
    title: 'Portobellos Rellenos de Salchicha',
    description: 'Disfruta de una versión saludable del clásico con estos Portobellos rellenos de salchicha.',
    image: 'https://www.vidaenbalance.com/wp-content/uploads/2024/06/PORTOBELLO-RELLENO-DE-SALCHICHA-673x890-1.jpg',
    ingredients: [
      '2 Portobellos',
      '1 Papa',
      '4 Salchichas de pavo San Rafael Balance®',
      'Cebolla',
    ],
    preparation: [
      'Desinfecta los portobellos y las verduras.',
      'Corta las salchichas de Pavo San Rafael Balance® y colócalas en un sarté Corta las papas en cuadros pequeños.',
      'Pon a cocer los portobellos y las papas.',
      'Agrega la cebolla a las salchichas.',
      'Sazona las salchichas con pimienta y sal.',
      'Una vez que los portobellos estén listos, agrega las salchichas y las verduras. ¡Buen provecho!',
    ],
    timePrep: '30 minutos',
    portions: '2 porciones',
    difficulty: 'Fácil',
    datePublished: '2025-01-01'
  },
  '11': {
    id: '11',
    title: 'Sándwich tostado de pechuga de pavo con manzana',
    description: 'Disfruta de un delicioso sándwich con sabores frescos con este sándwich tostado de pechuga de pavo con manzana.',
    image: 'https://www.vidaenbalance.com/wp-content/uploads/2024/06/SANDWICH-CON-JAMON-Y-MANZAN-672x890-1.jpg',
    ingredients: [
      'Pan blanco',
      'Pechuga de Pavo Rebanadas Cuadradas San Rafael Balance®',
      'Espinacas al gusto',
      '1 Manzana roja y 1 Manzana amarilla',
      'Mantequilla',
    ],
    preparation: [
      'Derrite un poco de mantequilla en un sartén.',
      'Coloca dos rebanadas de pan blanco sobre el sartén.',
      'Lava y desinfecta las espinacas y manzanas.',
      'Pica las manzanas en rodajas.',
      'Retira el pan blanco del sartén una vez que esté tostado.',
      'Coloca la manzana sobre una rebanada de pan, continua con 5 rebanadas cuadradas de Pechuga de Pavo rebanadas cuadradas San Rafael Balance®, encima pon las espinacas y cierra tu sándwich.',
    ],
    timePrep: '15-20 minutos',
    portions: '2 porciones',
    difficulty: 'Fácil',
    datePublished: '2025-01-01'
  },
  '12': {
    id: '12',
    title: 'Poke de quinoa con salchichas de pechuga de pavo',
    description: 'Disfruta de un delicioso poke con sabores frescos con este poke de quinoa con salchichas de pechuga de pavo.',
    image: 'https://www.vidaenbalance.com/wp-content/uploads/2023/06/Poke-de-quinoa-con-salchichas-de-pechuga-de-pavo.webp',
    ingredients: [
      '8 Salchichas de Pechuga de Pavo San Rafael® Balance® en rodajas',
      '1 taza de quinoa',
      '2 tazas de agua',
      '1 aguacate en láminas',
      '1 pepino en láminas delgadas',
      '½ taza de cherries partidos por mitad',
      '1 taza de edamames pelados',
      '1 zanahoria en láminas delgadas',
      'Sal y pimienta al gusto',
      'Aderezo de cilantro',
      '½ taza de mayonesa',
      '1 taza de hojas de cilantro',
      '1 cucharada de cebolla picada',
      '2 limones',
      '1 chile jalapeño sin semilla troceado',
      '3 cucharadas de pepita de calabaza',
    ],
    preparation: [
      'Lava la quinoa varias veces, escurre y coloca en una olla mediana con el agua. Calienta a fuego alto hasta que comience a hervir luego baja el fuego al mínimo y cuece durante 15 minutos.',
      'Para el aderezo licúa todos los ingredientes hasta obtener una textura tersa y salpimienta.',
      'Coloca una cama de quinoa en la base de cuatro platos y acomoda encima el resto de los ingredientes.',
      'Acompaña con el aderezo de cilantro y sirve.',
    ],
    timePrep: '30-35 minutos',
    portions: '4 porciones',
    difficulty: 'Media',
    datePublished: '2025-01-01'
  }
};

